name: drclin-frontend-prod

services:
  drclin-laundry:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL} # Toma el valor de las variables de Dokploy
    networks:
      - dokploy-network
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M

networks:
  dokploy-network:
    external: true